import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { Octokit } from '@octokit/rest';
import { execa } from 'execa';
import { simpleGit, type SimpleGit } from 'simple-git';
import type { FlaggedStatement } from '../types.js';

export interface PROptions {
  title: string;
  body: string;
  branch: string;
  baseBranch: string;
  files: Array<{ path: string; content: string }>;
  repoRoot?: string;
  commitMessage?: string;
  labels?: string[];
  assignees?: string[];
  reviewers?: string[];
}

export interface PRBodyOptions {
  flaggedStatements: FlaggedStatement[];
  confidence: number;
  reasoning: string;
}

export class PRCreationFallbackError extends Error {
  constructor(
    message: string,
    public readonly compareUrl: string | undefined,
    public readonly cause: unknown,
  ) {
    super(message);
    this.name = 'PRCreationFallbackError';
  }
}

interface GitHubRepo {
  owner: string;
  repo: string;
}

export async function createDriftguardPR(options: PROptions): Promise<string> {
  const repoRoot = options.repoRoot ?? process.cwd();
  const git = simpleGit(repoRoot);
  const originalRef = await getOriginalRef(git);
  const repo = await getGitHubRepo(git);
  const compareUrl = repo
    ? buildCompareUrl(repo, options.baseBranch, options.branch)
    : undefined;

  try {
    await git.raw(['checkout', '-b', options.branch]);
    writeFiles(repoRoot, options.files);
    await git.add(options.files.map((file) => toRepoRelativePath(repoRoot, file.path)));
    await git.commit(options.commitMessage ?? options.title);
    await git.raw(['push', '-u', 'origin', options.branch]);

    try {
      return await createPullRequestWithOctokit(repo, options);
    } catch (octokitError) {
      try {
        return await createPullRequestWithGh(repoRoot, options);
      } catch (ghError) {
        throw new PRCreationFallbackError(
          `Could not create a GitHub PR. Octokit failed, and gh CLI fallback was unavailable or failed.`,
          compareUrl,
          { octokitError, ghError },
        );
      }
    }
  } finally {
    await checkoutOriginalRef(git, originalRef);
  }
}

export function buildPRBranchName(commitHash: string, date = new Date()): string {
  const shortHash = (commitHash || '0000000').slice(0, 7).padEnd(7, '0');
  return `driftguard/${formatBranchTimestamp(date)}-${shortHash}`;
}

export function buildPRTitle(template: string, filename: string, trigger: string): string {
  return template
    .replaceAll('{filename}', filename)
    .replaceAll('{trigger}', trigger || 'context drift detected');
}

export function buildDriftguardPRBody(options: PRBodyOptions): string {
  const rows = buildFlaggedStatementRows(options.flaggedStatements);

  return `## 🔄 Context Drift Detected

driftguard detected that a recent commit may have made \`CLAUDE.md\` stale.

### What triggered this

| File Changed | Change Type | Statement Affected |
|---|---|---|
${rows || '| Unknown | modified | No statement details available |'}

### Proposed changes

${options.reasoning || 'driftguard generated a surgical context-file update.'}

### Confidence score: ${options.confidence.toFixed(2)}/1.0

---
*Generated by [driftguard](https://github.com/your-org/driftguard)*
*Review carefully before merging. driftguard proposes — you decide.*`;
}

export function buildTriggerSummary(commitMessage: string, fallback = 'context drift detected'): string {
  const firstLine = commitMessage.split(/\r?\n/).find((line) => line.trim());
  return firstLine?.trim().slice(0, 80) || fallback;
}

export async function resolveGitHubToken(): Promise<string | undefined> {
  if (process.env.GITHUB_TOKEN) {
    return process.env.GITHUB_TOKEN;
  }

  if (process.env.GH_TOKEN) {
    return process.env.GH_TOKEN;
  }

  try {
    const { stdout } = await execa('gh', ['auth', 'token']);
    return stdout.trim() || undefined;
  } catch {
    return undefined;
  }
}

export function parseGitHubRemote(remoteUrl: string): GitHubRepo | undefined {
  const normalized = remoteUrl.trim().replace(/\.git$/, '');
  const sshMatch = normalized.match(/^git@github\.com:(?<owner>[^/]+)\/(?<repo>.+)$/);
  const httpsMatch = normalized.match(/^https:\/\/github\.com\/(?<owner>[^/]+)\/(?<repo>.+)$/);
  const match = sshMatch ?? httpsMatch;
  const owner = match?.groups?.owner;
  const repo = match?.groups?.repo;

  if (!owner || !repo) {
    return undefined;
  }

  return { owner, repo };
}

function buildFlaggedStatementRows(flaggedStatements: FlaggedStatement[]): string {
  return flaggedStatements
    .flatMap((flagged) =>
      flagged.matchedChanges.map(
        (change) =>
          `| ${escapeTableCell(change.changedFilePath)} | ${change.changeType} | ${escapeTableCell(
            `Line ${flagged.statement.lineNumber}: ${flagged.statement.rawText}`,
          )} |`,
      ),
    )
    .join('\n');
}

function escapeTableCell(value: string): string {
  return value.replaceAll('|', '\\|').replace(/\r?\n/g, ' ');
}

async function getOriginalRef(git: SimpleGit): Promise<string> {
  const branch = (await git.raw(['rev-parse', '--abbrev-ref', 'HEAD'])).trim();

  if (branch && branch !== 'HEAD') {
    return branch;
  }

  return (await git.raw(['rev-parse', 'HEAD'])).trim();
}

async function checkoutOriginalRef(git: SimpleGit, originalRef: string): Promise<void> {
  try {
    await git.raw(['checkout', originalRef]);
  } catch {
    // A failed cleanup should not hide the original PR creation error.
  }
}

async function getGitHubRepo(git: SimpleGit): Promise<GitHubRepo | undefined> {
  try {
    const remoteUrl = await git.raw(['remote', 'get-url', 'origin']);
    return parseGitHubRemote(remoteUrl);
  } catch {
    return undefined;
  }
}

function writeFiles(repoRoot: string, files: PROptions['files']): void {
  for (const file of files) {
    const filePath = path.isAbsolute(file.path) ? file.path : path.join(repoRoot, file.path);
    mkdirSync(path.dirname(filePath), { recursive: true });
    writeFileSync(filePath, file.content);
  }
}

function toRepoRelativePath(repoRoot: string, filePath: string): string {
  return path.isAbsolute(filePath) ? path.relative(repoRoot, filePath) : filePath;
}

async function createPullRequestWithOctokit(
  repo: GitHubRepo | undefined,
  options: PROptions,
): Promise<string> {
  if (!repo) {
    throw new Error('Could not determine GitHub owner/repo from origin remote.');
  }

  const token = await resolveGitHubToken();
  if (!token) {
    throw new Error('No GitHub token available.');
  }

  const octokit = new Octokit({ auth: token });
  const pull = await octokit.pulls.create({
    owner: repo.owner,
    repo: repo.repo,
    title: options.title,
    body: options.body,
    head: options.branch,
    base: options.baseBranch,
  });

  await applyPullRequestMetadataBestEffort(octokit, repo, pull.data.number, options);
  return pull.data.html_url;
}

async function applyPullRequestMetadataBestEffort(
  octokit: Octokit,
  repo: GitHubRepo,
  pullNumber: number,
  options: PROptions,
): Promise<void> {
  await ignoreMetadataFailure(async () => {
    if (options.labels?.length) {
      await octokit.issues.addLabels({
        owner: repo.owner,
        repo: repo.repo,
        issue_number: pullNumber,
        labels: options.labels,
      });
    }
  });

  await ignoreMetadataFailure(async () => {
    if (options.assignees?.length) {
      await octokit.issues.addAssignees({
        owner: repo.owner,
        repo: repo.repo,
        issue_number: pullNumber,
        assignees: options.assignees,
      });
    }
  });

  await ignoreMetadataFailure(async () => {
    if (options.reviewers?.length) {
      await octokit.pulls.requestReviewers({
        owner: repo.owner,
        repo: repo.repo,
        pull_number: pullNumber,
        reviewers: options.reviewers,
      });
    }
  });
}

async function ignoreMetadataFailure(callback: () => Promise<void>): Promise<void> {
  try {
    await callback();
  } catch {
    // PR creation succeeded; metadata should not make the whole flow fail.
  }
}

async function createPullRequestWithGh(repoRoot: string, options: PROptions): Promise<string> {
  const args = [
    'pr',
    'create',
    '--title',
    options.title,
    '--body',
    options.body,
    '--base',
    options.baseBranch,
    '--head',
    options.branch,
  ];

  for (const label of options.labels ?? []) {
    args.push('--label', label);
  }

  for (const assignee of options.assignees ?? []) {
    args.push('--assignee', assignee);
  }

  for (const reviewer of options.reviewers ?? []) {
    args.push('--reviewer', reviewer);
  }

  const { stdout } = await execa('gh', args, { cwd: repoRoot });
  return stdout.trim();
}

function buildCompareUrl(repo: GitHubRepo, baseBranch: string, branch: string): string {
  return `https://github.com/${repo.owner}/${repo.repo}/compare/${encodeURIComponent(
    baseBranch,
  )}...${encodeURIComponent(branch)}?expand=1`;
}

function formatBranchTimestamp(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  return `${year}-${month}-${day}-${hours}${minutes}`;
}
